// Emit shadcn/ui component source files with OmD-derived theme variables applied.
//
// Scope (MVP):
//   theme/globals.css      — :root + .dark CSS variable blocks
//   lib/utils.ts           — cn() class-merge helper (required by every shadcn component)
//   components/ui/button.tsx
//   components/ui/card.tsx
//   components/ui/input.tsx
//   components/ui/index.ts — barrel export
//
// Radix-backed interactive primitives (Dialog, Popover, etc.) are delegated
// to radix-wrapper.ts per spec § 3. This module owns the static shells only.

import type { ParsedDesign, PlannedWrite, ComponentId } from './types.js';
import { RADIX_BACKED } from './types.js';
import { emitRadixWrapper } from './radix-wrapper.js';

export interface EmitShadcnOptions {
  design: ParsedDesign;
  components: ComponentId[];
}

export function emitShadcn(opts: EmitShadcnOptions): PlannedWrite[] {
  const writes: PlannedWrite[] = [];

  writes.push({
    path: 'theme/globals.css',
    contents: renderThemeCss(opts.design),
    kind: 'theme',
  });

  writes.push({
    path: 'theme/tailwind.preset.js',
    contents: renderTailwindPreset(opts.design),
    kind: 'theme',
  });

  writes.push({
    path: 'lib/utils.ts',
    contents: UTILS_TS,
    kind: 'config',
  });

  for (const id of opts.components) {
    if (RADIX_BACKED.has(id)) {
      const radixWrite = emitRadixWrapper(id, opts.design);
      if (radixWrite) writes.push(radixWrite);
      continue;
    }
    const staticWrite = emitStaticComponent(id);
    if (staticWrite) writes.push(staticWrite);
  }

  writes.push({
    path: 'components/ui/index.ts',
    contents: renderBarrel(opts.components),
    kind: 'index',
  });

  return writes;
}

// ── theme/globals.css ────────────────────────────────────────────

export function renderThemeCss(design: ParsedDesign): string {
  const lines: string[] = [];
  lines.push('/* Generated by omd-ultra from ' + design.name + '. Do not edit by hand. */');
  lines.push('@layer base {');
  lines.push('  :root {');
  for (const [k, v] of Object.entries(design.theme.light)) {
    lines.push(`    ${k}: ${v};`);
  }
  lines.push('  }');
  if (design.theme.dark) {
    lines.push('');
    lines.push('  .dark {');
    for (const [k, v] of Object.entries(design.theme.dark)) {
      lines.push(`    ${k}: ${v};`);
    }
    lines.push('  }');
  }
  lines.push('}');
  lines.push('');
  lines.push('@layer base {');
  lines.push('  * { border-color: hsl(var(--border)); }');
  lines.push('  body { background-color: hsl(var(--background)); color: hsl(var(--foreground)); }');
  lines.push('}');
  return lines.join('\n') + '\n';
}

// ── theme/tailwind.preset.js ─────────────────────────────────────
//
// Emitted as a Tailwind preset (not a full config) so users can merge it
// into their existing `tailwind.config.{js,ts}` via the `presets: [...]`
// array. We expose:
//   - colors wired to the HSL CSS variables in globals.css
//   - borderRadius.DEFAULT = var(--radius)
//   - fontFamily.{sans,mono} = var(--font-sans|--font-mono)
//   - transitionDuration and transitionTimingFunction = motion tokens
// All reference the CSS variables, so re-scaffolding theme only touches
// globals.css; the preset stays stable.

export function renderTailwindPreset(_design: ParsedDesign): string {
  return `/* Generated by omd-ultra. Merge into tailwind.config.js via \`presets: [require('./theme/tailwind.preset')]\`. */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        emphasized: 'var(--ease-emphasized)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down var(--duration-normal) var(--ease-standard)',
        'accordion-up': 'accordion-up var(--duration-normal) var(--ease-standard)',
      },
    },
  },
};
`;
}

// ── Static component sources ─────────────────────────────────────

const UTILS_TS = `import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

const BUTTON_TSX = `import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const buttonVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-[var(--radius)] text-sm font-medium ring-offset-[hsl(var(--background))] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] hover:opacity-90',
        destructive: 'bg-[hsl(var(--destructive))] text-[hsl(var(--destructive-foreground))] hover:opacity-90',
        outline: 'border border-[hsl(var(--border))] bg-[hsl(var(--background))] hover:bg-[hsl(var(--accent))] hover:text-[hsl(var(--accent-foreground))]',
        secondary: 'bg-[hsl(var(--secondary))] text-[hsl(var(--secondary-foreground))] hover:opacity-90',
        ghost: 'hover:bg-[hsl(var(--accent))] hover:text-[hsl(var(--accent-foreground))]',
        link: 'text-[hsl(var(--primary))] underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 px-3',
        lg: 'h-11 px-8',
        icon: 'h-10 w-10',
      },
    },
    defaultVariants: { variant: 'default', size: 'default' },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => (
    <button
      ref={ref}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  ),
);
Button.displayName = 'Button';

export { buttonVariants };
`;

const CARD_TSX = `import * as React from 'react';
import { cn } from '@/lib/utils';

export const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        'rounded-[var(--radius)] border border-[hsl(var(--border))] bg-[hsl(var(--card))] text-[hsl(var(--card-foreground))] shadow-sm',
        className,
      )}
      {...props}
    />
  ),
);
Card.displayName = 'Card';

export const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('flex flex-col space-y-1.5 p-6', className)} {...props} />
  ),
);
CardHeader.displayName = 'CardHeader';

export const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3 ref={ref} className={cn('text-2xl font-semibold leading-none tracking-tight', className)} {...props} />
  ),
);
CardTitle.displayName = 'CardTitle';

export const CardDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(
  ({ className, ...props }, ref) => (
    <p ref={ref} className={cn('text-sm text-[hsl(var(--muted-foreground))]', className)} {...props} />
  ),
);
CardDescription.displayName = 'CardDescription';

export const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('p-6 pt-0', className)} {...props} />
  ),
);
CardContent.displayName = 'CardContent';

export const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('flex items-center p-6 pt-0', className)} {...props} />
  ),
);
CardFooter.displayName = 'CardFooter';
`;

const INPUT_TSX = `import * as React from 'react';
import { cn } from '@/lib/utils';

export type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => (
    <input
      type={type}
      ref={ref}
      className={cn(
        'flex h-10 w-full rounded-[var(--radius)] border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2 text-sm ring-offset-[hsl(var(--background))] placeholder:text-[hsl(var(--muted-foreground))] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      {...props}
    />
  ),
);
Input.displayName = 'Input';
`;

const STATIC_SOURCES: Partial<Record<ComponentId, string>> = {
  button: BUTTON_TSX,
  card: CARD_TSX,
  input: INPUT_TSX,
};

function emitStaticComponent(id: ComponentId): PlannedWrite | null {
  const src = STATIC_SOURCES[id];
  if (!src) return null;
  return {
    path: `components/ui/${id}.tsx`,
    contents: src,
    kind: 'component',
  };
}

// ── Barrel ───────────────────────────────────────────────────────

function renderBarrel(ids: ComponentId[]): string {
  const lines = ids.map((id) => `export * from './${id}';`);
  return lines.join('\n') + '\n';
}
